services:
  code-init:
    image: alpine:3.20
    command: >
      sh -lc '
        mkdir -p /home/linuxuser/wa-crm/sessions &&
        mkdir -p /home/linuxuser/wa-crm/media &&
        mkdir -p /home/linuxuser/wa-crm/meta-media &&
        mkdir -p /home/linuxuser/wa-crm/client/public &&
        chown -R 33:33 /home/linuxuser/wa-crm/sessions /home/linuxuser/wa-crm/media /home/linuxuser/wa-crm/meta-media /home/linuxuser/wa-crm/client/public &&
        chmod -R 775 /home/linuxuser/wa-crm/sessions /home/linuxuser/wa-crm/media /home/linuxuser/wa-crm/meta-media /home/linuxuser/wa-crm/client/public &&
      '
    volumes:
      - /home/linuxuser/wa-crm:/home/linuxuser/wa-crm
    restart: "no"

  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    restart: unless-stopped
    # ports:
    #   - "${PORT:-3010}:3010"
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - .env
    # environment:
    #   # Database Configuration
    #   DBHOST: ${DBHOST:-localhost}
    #   DBPORT: ${DBPORT:-3306}
    #   DBUSER: ${DBUSER:-root}
    #   DBPASS: ${DBPASS:-}
    #   DBNAME: ${DBNAME:-wa_crm}
    #   
    #   # Application Configuration
    #   PORT: 3010
    #   NODE_ENV: ${NODE_ENV:-production}
    #   
    #   # JWT Configuration
    #   JWTKEY: ${JWTKEY:-your-super-secret-jwt-key-change-this}
    #   
    #   # Frontend/Backend URLs
    #   FRONTENDURI: ${FRONTENDURI:-http://localhost:3010}
    #   BACKURI: ${BACKURI:-http://localhost:3010}
    #   
    #   # Stripe Configuration (Optional)
    #   STRIPE_LANG: ${STRIPE_LANG:-en}
    #   
    #   # Email Configuration (Optional)
    #   EMAIL_HOST: ${EMAIL_HOST:-}
    #   EMAIL_PORT: ${EMAIL_PORT:-587}
    #   EMAIL_USER: ${EMAIL_USER:-}
    #   EMAIL_PASS: ${EMAIL_PASS:-}
    #   
    #   # AI API Keys (Optional)
    #   OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    #   GEMINI_API_KEY: ${GEMINI_API_KEY:-}
    #   DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY:-}
    #   
    #   # WhatsApp Business API (Optional)
    #   META_ACCESS_TOKEN: ${META_ACCESS_TOKEN:-}
    #   META_VERIFY_TOKEN: ${META_VERIFY_TOKEN:-}
      
    volumes:
      - /home/linuxuser/wa-crm/sessions:/app/sessions
      - /home/linuxuser/wa-crm/media:/app/media
      - /home/linuxuser/wa-crm/meta-media:/app/meta-media
      - /home/linuxuser/wa-crm/client/public:/app/client/public
    networks:
      - wa-crm-network

networks:
  wa-crm-network:
    driver: bridge
