services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "${PORT:-3010}:3010"
    env_file:
      - .env
    networks:
      - wa-crm-network

networks:
  wa-crm-network:
    driver: bridge
